version: '3.8'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  blazorapp:
    build: .
    hostname: blazorapp
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:8080" 
    depends_on:
      - mongodb

volumes:
  mongo-data:
